-- Kaiten automations (Phase 4): per-project rules. Purely additive — two enums
-- + one table. (Stripped Prisma's spurious Message.searchVector / raw-SQL index
-- drops from the autogenerated diff; those are managed outside Prisma.)

-- CreateEnum
CREATE TYPE "AutomationTrigger" AS ENUM ('CARD_ENTERS_COLUMN');

-- CreateEnum
CREATE TYPE "AutomationActionType" AS ENUM ('SET_ASSIGNEE', 'SET_PRIORITY', 'ADD_COMMENT', 'SET_SWIMLANE');

-- CreateTable
CREATE TABLE "AutomationRule" (
    "id" TEXT NOT NULL,
    "projectId" TEXT NOT NULL,
    "name" TEXT NOT NULL,
    "enabled" BOOLEAN NOT NULL DEFAULT true,
    "trigger" "AutomationTrigger" NOT NULL,
    "triggerConfig" JSONB NOT NULL,
    "actionType" "AutomationActionType" NOT NULL,
    "actionConfig" JSONB NOT NULL,
    "order" INTEGER NOT NULL DEFAULT 0,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "AutomationRule_pkey" PRIMARY KEY ("id")
);

-- CreateIndex
CREATE INDEX "AutomationRule_projectId_enabled_idx" ON "AutomationRule"("projectId", "enabled");

-- AddForeignKey
ALTER TABLE "AutomationRule" ADD CONSTRAINT "AutomationRule_projectId_fkey" FOREIGN KEY ("projectId") REFERENCES "Project"("id") ON DELETE CASCADE ON UPDATE CASCADE;
