-- Kaiten sub-columns: additive — new BoardSubColumn table + a nullable
-- Task.subColumnId (metadata-only add, no table rewrite, zero row mutation).
-- The dormant Task index is intentionally left unchanged. (Stripped Prisma's
-- spurious Message.searchVector / raw-index drops from the autogenerated diff —
-- those are managed outside Prisma.)

-- AlterTable
ALTER TABLE "Task" ADD COLUMN     "subColumnId" TEXT;

-- CreateTable
CREATE TABLE "BoardSubColumn" (
    "id" TEXT NOT NULL,
    "columnId" TEXT NOT NULL,
    "name" TEXT NOT NULL,
    "order" INTEGER NOT NULL,
    "wipLimit" INTEGER,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "BoardSubColumn_pkey" PRIMARY KEY ("id")
);

-- CreateIndex
CREATE INDEX "BoardSubColumn_columnId_order_idx" ON "BoardSubColumn"("columnId", "order");

-- CreateIndex
CREATE UNIQUE INDEX "BoardSubColumn_columnId_name_key" ON "BoardSubColumn"("columnId", "name");

-- AddForeignKey
ALTER TABLE "Task" ADD CONSTRAINT "Task_subColumnId_fkey" FOREIGN KEY ("subColumnId") REFERENCES "BoardSubColumn"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "BoardSubColumn" ADD CONSTRAINT "BoardSubColumn_columnId_fkey" FOREIGN KEY ("columnId") REFERENCES "BoardColumn"("id") ON DELETE CASCADE ON UPDATE CASCADE;
