-- Add the TASK_CREATED automation trigger value. Additive enum extension.
-- (Stripped Prisma's spurious Message.searchVector / raw-index drops from the
-- autogenerated diff — they're managed outside Prisma.)

-- AlterEnum
ALTER TYPE "AutomationTrigger" ADD VALUE 'TASK_CREATED';
